# Autogenerated wrapper script for Clay_jll for aarch64-apple-darwin
export libclay

JLLWrappers.@generate_wrapper_header("Clay")
JLLWrappers.@declare_library_product(libclay, "@rpath/libclay.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libclay,
        "lib/libclay.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
