# Autogenerated wrapper script for Clay_jll for aarch64-unknown-freebsd
export libclay

JLLWrappers.@generate_wrapper_header("Clay")
JLLWrappers.@declare_library_product(libclay, "libclay.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libclay,
        "lib/libclay.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
